version: 1
formatters:
  precise:
    format: 'Bonjour %(asctime)s - %(name)s - %(levelname)s - %(message)s'
  brief:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s'
handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: precise
  file:
    level: DEBUG
    class: logging.FileHandler
    formatter: precise
root:
  handlers:
    - file
    - console
