version: 1
formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  brief:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s'
handlers:
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: brief
  file:
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    formatter: precise
    mode: a
    maxBytes: 2500000
    backupCount: 1
root:
  level: DEBUG
  handlers:  [console, file]
